# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Azure Extension for TTT AutoRun15@0
  inputs:
    HCIConnection: 'CW01.bmc.com'
    HCIConnectionPort: '16196'
    UserID: 'PINAWM1'
    Password: '$(Password)'
    PassTicket: 'passticket'
    TestLocationPath: 'C:\Users\amohapat\Compuware\Workbench\workspace\ZENG-266377-POC\Tests\Scenarios\SQLSelectScenario.context'
    CLIInstallationPath: 'C:\Topaz\WorkbenchCLI\20.12.02.99\'
    Environment: 'CW01-16196 Batch'
    Repository: 'http://vw-dtw-xat-01.adprod.bmc.com:48231/totaltestapi/'
    LocalTTTConfiguration: 'C:\Topaz\TotalTestConfiguration'
    Configuration: 'LocalTTTConfiguration'
