# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Azure Extension for TTT AutoRun7@0
  inputs:
      HCIConnection: 'CW01.bmc.com'
      HCIConnectionPort: '16196'
      UserID: 'pinawm1'
      Password: 'Moab22'
      PassTicket: 'passticket'
      TestLocationPath: 'C:\Users\amohapat\Testing\CLITestInAzureExt\Scenarios\ZENG-266377-Test.context'
      CLIInstallationPath: 'C:\Topaz\WorkbenchCLI\20.12.02.99\'
      Configuration: 'C:\Topaz\TotalTestConfiguration'
